name: "Frogbot PR Scan"
on:
  pull_request:
    branches: ["main"]
permissions:
  id-token: write
  contents: read
  pull-requests: write
jobs:
  frogbot-scan:
    runs-on: ubuntu-latest
    environment: frogbot
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup JFrog CLI (OIDC)
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JF_URL }}
        with:
          oidc-provider-name: github-oidc
      - name: Run Frogbot Scan
        uses: jfrog/frogbot@v2
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JFROG_CLI_LOG_LEVEL: "DEBUG"
          JF_INCLUDE_ALL_VULNERABILITIES: "true"
          JF_FAIL: "false"
          FROGBOT_LOG_LEVEL: "DEBUG"
