name: "JFrog Python Example"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
permissions:
  id-token: write
  contents: write
  pull-requests: write
  actions: read
  security-events: write
env:
  BUILD_NAME: "JFrog-Scan-Example-Build"
  BUILD_NUMBER: "${{ github.run_number }}"
jobs:
  build-scan:
    runs-on: ubuntu-latest
    environment: frogbot
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.9"
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            gcc \
            python3-dev \
            libxml2-dev \
            libxslt1-dev \
            zlib1g-dev \
            libjpeg-dev \
            libtiff-dev \
            libfreetype6-dev \
            liblcms2-dev \
            libwebp-dev \
            libopenjp2-7-dev \
            tcl8.6-dev tk8.6-dev
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JF_URL }}
        with:
          oidc-provider-name: github-oidc
      - name: Configure pip
        run: |
          jf pip-config \
            --repo-resolve=sws-jf-example-python-remote \
            --server-id-resolve=setup-jfrog-cli-server
      - name: Install Python Dependencies
        run: |
          export PIP_DEFAULT_TIMEOUT=120
          export PIP_EXTRA_INDEX_URL=https://pypi.org/simple
          jf pip install build --retries 10
          jf pip install -r requirements.txt \
            --build-name $BUILD_NAME \
            --build-number $BUILD_NUMBER \
            --project=jf-example \
            --retries 10
      - name: Build artifact
        run: |
          python -m build
      - name: Upload artifact and build info
        run: |
          jf rt bce $BUILD_NAME $BUILD_NUMBER --project=jf-example
          jf rt upload "dist/*" "sws-jf-example-python-local" \
            --build-name $BUILD_NAME \
            --build-number $BUILD_NUMBER \
            --project=jf-example
          jf rt bad $BUILD_NAME $BUILD_NUMBER requirements.txt --project=jf-example
          jf rt bp $BUILD_NAME $BUILD_NUMBER --project=jf-example
      - name: Run Xray scan
        run: |
          jf build-scan $BUILD_NAME $BUILD_NUMBER \
            --format=sarif \
            --project=jf-example > jfrog_scan_results.sarif
      - name: Xray dependency audit
        run: |
          jf audit --format=sarif > jfrog_audit_results.sarif
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: jfrog_scan_results.sarif
